version: '2'
services:
    cmp-api-openstack-mysql:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/microserviceApp1/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=monitor
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
